PeerEvaluationTool/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # New login session
  get 'sessions/new'

  # Set our root page to our about page
  root 'static_pages#about'

  # Static page routes
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'home' => 'static_pages#home'

  # Signup/Login routes
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # Have our home page be our user page
  post 'users/:id' => 'static_pages#home'

  # Create a new rating when submitted
  post 'ratings' => 'ratings#create'
  
  # Have user resource accessible
  resources :users
end

PeerEvaluationTool/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

PeerEvaluationTool/app/models/group.rb
class Group < ApplicationRecord
end

PeerEvaluationTool/app/models/rating.rb
class Rating < ApplicationRecord
end

PeerEvaluationTool/app/models/user.rb
# User input validation for sign-ups
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }

  EMAIL_FORMAT = URI::MailTo::EMAIL_REGEXP
  validates :email, length: { maximum: 255 },
            format: { with: EMAIL_FORMAT },
            uniqueness: { case_sensitive: false }
  has_secure_password(options={validations:false})
  validates :password, presence: true, on: :create
  validates :user_grade, presence: false, length: {maximum: 2}
end

PeerEvaluationTool/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

PeerEvaluationTool/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  # Shows a given rating
  def show
    @rating = Rating.find(params[:id])
  end

  # Create new rating with instance variable @rating
  def new
    @rating = Rating.new
  end

  # Attempts to create and save a rating to the db based on input
  def create
    @rating = Rating.new(rating_params)
    if @rating.save
      flash.now[:success] = 'Submitted'
    else
      flash.now[:failure] = 'Error'

    end
  end

  # Private rating parameters
  private
  def rating_params
    params.permit(:score, :group_no, :rater, :ratee, :rater_comments, :project_no)
  end

end

PeerEvaluationTool/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  # Creates a new session for user if login params are valid
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_to user
    else
      flash.now[:danger] = 'Incorrect Login Information'
      render 'new'
    end
  end

  # Logs out user and returns to root page
  def destroy
    logout
    redirect_to root_url

  end
end

PeerEvaluationTool/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

PeerEvaluationTool/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Displays user with given parameter and group/teammates with instance variables @user, @group, @teammates
  def show
    @user = User.find(params[:id])
    t = @user.group_no
    @group = Group.find_by(group_number:t)
    @teammates = User.where(group_no:t)

  end

  # Creates new user with instance variable @user
  def new
    @user = User.new
  end

  # Creates a new user and attempts to save them into the db
  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      flash.now[:success] = 'Thanks for signing up!'
      redirect_to @user
    else
      render 'new'
    end
  end

  # Update user information
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Settings changed"
      redirect_to @user
    else
      render 'edit'
    end
  end

  # Edit user information
  def edit
    @user = User.find(params[:id])
  end

  # Private method for user parameters
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

PeerEvaluationTool/app/helpers/application_helper.rb
module ApplicationHelper
end

PeerEvaluationTool/app/helpers/ratings_helper.rb
module RatingsHelper
end

PeerEvaluationTool/app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in to a user
  def login(user)
    session[:user_id] = user.id
  end

  # Returns current user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if @current_user.nil?
  end

  # Checks if user is logged in
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out user
  def logout
    session.delete(:user_id)
    @current_user = nil
  end

end

PeerEvaluationTool/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

PeerEvaluationTool/app/helpers/users_helper.rb
module UsersHelper
end

PeerEvaluationTool/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%# creating a navbar for page %>
  <body>
  <header class = "navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%# creating navbar for logged in user %>
      <% if logged_in?%>
        <%=link_to("DOGME Peer Evaluation Tool", @current_user, id: "title_button") %>
        <nav>
          <ul class = "nav navbar-nav navbar-right">
            <li><%=link_to "About", about_path %></li>
            <li><%=link_to "Help", help_path %></li>
            <li><%=link_to "Profile", @current_user %></li>
            <li><%=link_to "Settings", edit_user_path(@current_user) %></li>
            <li><%=link_to "Logout", logout_path, method: "delete" %></li>
          </ul>
        </nav>
      <% else %>
        <%# creating navbar for not logged in user %>
        <%=link_to("DOGME Peer Evaluation Tool", root_path, id: "title_button") %>
        <nav>
          <ul class = "nav navbar-nav navbar-right">
            <li><%=link_to "About", about_path %></li>
            <li><%=link_to "Help", help_path %></li>
            <li><%=link_to "Signup", home_path %></li>
            <li><%=link_to "Login", login_path %></li>
          </ul>
        </nav>
      <%end %>
    </div>
  </header>

  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type%>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

PeerEvaluationTool/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger", id="error_explanation">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </div>
<% end %>

PeerEvaluationTool/app/views/static_pages/about.html.erb
<%#Information for the about page for the user%>
<% provide(:title, "DOGME") %>

<header class = "navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in?%>
      <%=link_to("DOGME Peer Evaluation Tool", @current_user, id: "title_button") %>
      <nav>
        <ul class = "nav navbar-nav navbar-right">
          <li><%=link_to "About", about_path %></li>
          <li><%=link_to "Help", help_path %></li>
          <li><%=link_to "Profile", @current_user %></li>
          <li><%=link_to "Settings", edit_user_path(@current_user) %></li>
          <li><%=link_to "Logout", logout_path, method: "delete" %></li>
        </ul>
      </nav>
    <% else %>
      <%=link_to("DOGME Peer Evaluation Tool", root_path, id: "title_button") %>
      <nav>
        <ul class = "nav navbar-nav navbar-right">
          <li><%=link_to "About", about_path %></li>
          <li><%=link_to "Help", help_path %></li>
          <li><%=link_to "Signup", home_path %></li>
          <li><%=link_to "Login", login_path %></li>
        </ul>
      </nav>
    <%end %>
  </div>
</header>


<div class="center jumbotron">
  <div id="about_page">
    <h1>DOGME</h1>
    <%= image_tag "dogme3.png", height: 500 %>
    <p>This peer evaluation tool was developed by MAMAS MIA for the CSE 3901 Final Project in 2021.</p>
    <p>Inspiration for the site came from <a href="https://catme.org/login/index">Purdue's CATME</a> system.</p>
    <% if logged_in? == false%>
      <p><strong>*Click signup on the top right of your screen to create an account now!*</strong></p>
    <%end %>
      </div>
</div>

PeerEvaluationTool/app/views/static_pages/help.html.erb
<%#Information for the help page for the user%>

<% provide(:title, "Help") %>
<div class="center jumbotron">
  <div id="help_page">
    <h1>Help</h1>
    <h2>
      <li>Once you create an account, an instructor will be able to add you to a group.</li>
      <li>Reach out to your instructor if you are having issues accessing your group or signing up.</li>
      <li>Contact an admin if you are an instructor and need admin privileges give to you.</li>
    </h2>
  </div>
</div>

PeerEvaluationTool/app/views/static_pages/home.html.erb
<%#Information for the home page for the user%>
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>DOGME</h1>
  <h2>The Peer Evaluation Tool for everyone.</h2>
  <%#In case if the user is not logged in%>
  <% if logged_in? == false%>
      <%=link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

PeerEvaluationTool/app/views/users/edit.html.erb
<% # This is the page for new users before being entered into the database%>
<% provide(:title, "Edit Profile") %>
<div class="static_message">
  <h1>Edit your profile:</h1>
  <h4>Change any of the field below to update your information.</h4>
  <h4>Some field may already be filled out. Entering a different password will change your current one.</h4>
  <h4>Press 'Save' to save the changes.</h4>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages'%>

      <%#First Name%>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%#Last Name%>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%#Email%>
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%#Password%>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

PeerEvaluationTool/app/views/users/new.html.erb
<% # This is the page for new users before being entered into the database%>
<% provide(:title, "Signup") %>
<div class= "static_message">
  <h1>Fill in the information below to sign up:</h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages'%>
      
      <%#First Name%>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%#Last Name%>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%#Email%>
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%#Password%>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.submit "Finish", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

PeerEvaluationTool/app/views/users/show.html.erb
<%# This is the profile page for the current user %>

<div class="center jumbotron">
  <h1> Welcome <%= @user.first_name %> <%= @user.last_name %>!</h1>

  <%# Displays link to admin dashboard if the user is an admin %>
  <% if @user.admin %>
    <h2>Click below to access your admin dashboard:</h2>
    <h2><%=link_to "Admin Dashboard", rails_admin_path %></h2>
  <%end %>
</div>

<ul class="jumbotron" id="rating_field">
  <%# check if user is not an admin %>
  <% if !@user.admin %>
    <%# if user has a grade, then display the grade %>
    <% if @user.user_grade != nil %>
      <h2>Your current grade is: <%= @user.user_grade.upcase %></h2>
    <% else %>
      <h2>You have not been assigned a grade yet!</h2>
    <% end %>

    <%# Checks if the user has a group assigned %>
    <% if @user.group_no != nil %>
      <%# if user has a group, then displays the name and number %>
      <h2>Your group is <%= Group.find_by(group_number: @user.group_no).group_name%> (Group #<%= @user.group_no%>)  </h2>
      <h3> Rate your group members below: </h3>
      <div class="spacer">--------------------------------------------------------------------------------------</div>
    <%else%>
      <%# if user does not have group, then display general info %>
      <h2>Contact your instructor to get added to a group.</h2>
    <% end %>

    <% if @user.group_no != nil %>
      <%# displays the group members and gives them a form with ratings and comments to fill out for a project %>
      <% @teammates.each do |x| %>
        <%# in case an admin is assigned a group, it should not give them a rating %>
        <% unless x.admin %>
          <h2><%= x.first_name %> <%= x.last_name %></h2>
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <%# access the rating controller to save the ratings by the user for each user %>
              <%= form_with(model: @rating, url: {controller:'ratings', action:'create'}) do |r| %>

                <%#Project%>
                <%= r.label :project_no, "Project #" %>
                <%= r.number_field :project_no%>

                <%#Score%>
                <%= r.label :score %>
                <%= r.range_field :score, in:1..10, :step=>'.1' %>
                <p>1 ---- 2   ----  3   ----  4    ----   5   ----    6   ----    7   ----    8    ----   9  ----   10</p>

                <%#Comment%>
                <%= r.label :rater_comments %>
                <%= r.text_field :rater_comments %>

                <%# send user's name, group number, and teammates name and keep them hidden from user %>
                <%= r.hidden_field :group_no, value: @user.group_no %>
                <%= r.hidden_field :rater, value: (@user.first_name + " " + @user.last_name) %>
                <%= r.hidden_field :ratee, value: (x.first_name + " " + x.last_name) %>

                <%# submit button %>
                <%= r.submit "Submit", class: "btn btn-primary", 'data-disable-with' => "Submitted"%>
              <% end %>
            </div>
          </div>
          <%# lines to show cutoff for each group member %>
          <div class="spacer">--------------------------------------------------------------------------------------</div>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <%# if user is admin display general admin info %>
    <h3>From the admin panel you can view ratings, assign users to groups, create new users, and more.</h3>
  <% end %>
</ul>